rm -Rf CMakeCache.txt

cmake -D CMAKE_INSTALL_PREFIX=/Users/pete/Temp/spdtest/ \
-D HDF5_INCLUDE_DIR=$HDF5_INCLUDE_PATH \
-D HDF5_LIB_PATH=$HDF5_LIB_PATH \
-D LIBLAS_INCLUDE_DIR=$LIBLAS_INCLUDE_PATH \
-D LIBLAS_LIB_PATH=$LIBLAS_LIB_PATH \
-D GSL_INCLUDE_DIR=$GSL_INCLUDE_PATH \
-D GSL_LIB_PATH=$GSL_LIB_PATH \
-D CGAL_INCLUDE_DIR=$CGAL_INCLUDE_PATH \
-D CGAL_LIB_PATH=$CGAL_LIB_PATH \
-D BOOST_INCLUDE_DIR=$BOOST_INCLUDE_PATH \
-D BOOST_LIB_PATH=$BOOST_LIB_PATH \
-D GDAL_INCLUDE_DIR=$GDAL_INCLUDE_PATH \
-D GDAL_LIB_PATH=$GDAL_LIB_PATH \
-D XERCESC_INCLUDE_DIR=$XERCESC_INCLUDE_PATH \
-D XERCESC_LIB_PATH=$XERCESC_LIB_PATH \
-D GMP_INCLUDE_DIR=$GMP_INCLUDE_PATH \
-D GMP_LIB_PATH=$GMP_LIB_PATH \
-D MPFR_INCLUDE_DIR=$MPFR_INCLUDE_PATH \
-D MPFR_LIB_PATH=$MPFR_LIB_PATH \
-D SPDLIB_INCLUDE_DIR=$SPDLIB_INCLUDE_PATH \
-D SPDLIB_LIB_PATH=$SPDLIB_LIB_PATH \
.

make 
